language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r tests/test_requirements.txt
# command to run tests
before_script:
  - python tests/rsshttp.py &
script: pytest tests/